apiVersion: v1
kind: Secret
metadata:
  name: crowdstrike-credentials
  namespace: aspm-inventory
  labels:
    app: aspm-service-inventory
type: Opaque
stringData:
  client-id: "your_client_id_here"
  client-secret: "your_client_secret_here"